# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0101f8988e2fb1ddd7fa04af0dcd64a4327fe907d64228498702d4a79031af8c609ef719a83863195f8c6c6576b857c344276ff8368c76f426c16aa0858444f

test:
  secret_key_base: 3856aa467ccf87696c47b75994a07a74d6721c6f3b4bcedd69c323595622e9d093a7de3fbace6813e27ed43d9c41f055d06b140789d6ff13a030b541ae0adf36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
